// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCYEiAddYw8VXhfjyhicxO3Qi0jYOuJnM',
    appId: '1:825010792860:android:e990b667b0e7b9972d0059',
    messagingSenderId: '825010792860',
    projectId: 'id-lestari-project',
    storageBucket: 'id-lestari-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChDAnHSYD2vv2yJ25vakDIbjj526tc49k',
    appId: '1:825010792860:ios:7b3c5da58aa322842d0059',
    messagingSenderId: '825010792860',
    projectId: 'id-lestari-project',
    storageBucket: 'id-lestari-project.firebasestorage.app',
    iosBundleId: 'com.example.lestarUser',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe9lGU5ipFZqBXHED3VDoTmr4NkurOnSI',
    appId: '1:825010792860:web:56b9bc25291894162d0059',
    messagingSenderId: '825010792860',
    projectId: 'id-lestari-project',
    authDomain: 'id-lestari-project.firebaseapp.com',
    storageBucket: 'id-lestari-project.firebasestorage.app',
  );

}